baseURL = 'https://madeleinetan.github.io/'
languageCode = 'en-us'
title = 'Madeleine Tan'
theme = 'hugo-astatine-theme'

preserveTaxonomyNames = true
rssLimit = 10
paginate = 10

pygmentsCodefences = true
pygmentsStyle = 'native'

[taxonomies]
	category = 'categories'

[permalinks]
	page = '/:slug/'
	post = '/:slug/'

[[menu.main]]
	name = 'CV'
	url = '/docs/madeleinetan_cv.pdf'
	weight = -110

[[menu.main]]
	name = 'Projects'
	url = '/projects/'
	weight = -130

[[menu.main]]
	name = 'Software'
	url = '/software/'
	weight = -120

[params]
	description = """Madeleine Tan website"""
	authorName = "Madeleine Tan"
	[params.imgname]
		name = 'images/profilePic2.jpg'
		alt = 'Profile Picture'

	blogrss = true

[sitemap]
	filename = 'sitemap.xml'
